import { NextResponse } from "next/server";

export const shoes = [
  {
    id: 1,
    name: "Nike Air Force 1 Low '07 White",
    description: "Classic, White, Flexible",
    brand: "Nike",
    image: "/shoes/AF1.avif",
    price: "$67",
    stock: "21",
  },
  {
    id: 2,
    name: "Nike Kobe 6 Protro Grinch (2020)",
    description: "High Performance and Flashy on Court",
    brand: "Nike",
    image: "/shoes/grinch.avif",
    price: "$663",
    stock: "4",
  },
  {
    id: 3,
    name: "adidas Samba OG Footwear White Green",
    description: "Stylist Footwear for Daily Use",
    brand: "adidas",
    image: "/shoes/sambagreen.avif",
    price: "$51",
    stock: "10",
  },
  {
    id: 4,
    name: "adidas Yeezy Foam RNR Stone Salt",
    description: "Comfortable and Odd Looking",
    brand: "adidas",
    image: "/shoes/foamrunnersalt.avif",
    price: "$70",
    stock: "8",
  },
  {
    id: 5,
    name: "Jordan 1 Retro High Off-White University Blue",
    description: "Can't Go Wrong with some Jordan 1 UNC Blue",
    brand: "Jordan",
    image: "/shoes/offwhiteunc.avif",
    price: "$880",
    stock: "2",
  },
  {
    id: 6,
    name: "Jordan 4 Retro Black Cat (2020)",
    description: "Nice Black and Aggresive Sneaker",
    brand: "Jordan",
    image: "/shoes/blackcat.avif",
    price: "$724",
    stock: "3",
  },
  {
    id: 7,
    name: "Jordan 1 Retro High OG Chicago Lost and Found",
    description: "Felt Old, but still Good Lookin' shoes",
    brand: "Jordan",
    image: "/shoes/chicagol&f.avif",
    price: "$124",
    stock: "8",
  },
  {
    id: 8,
    name: "Nike Kobe 6 Protro Reverse Grinch",
    description: "Reversed, but still High Performance and Flashy on Court",
    brand: "Nike",
    image: "/shoes/reversegrinch.avif",
    price: "$254",
    stock: "5",
  },
  {
    id: 9,
    name: "adidas Yeezy Slide Onyx (2023)",
    description: "Lightweight and Comfortable Slides",
    brand: "adidas",
    image: "/shoes/slideonyx.avif",
    price: "$62",
    stock: "10",
  },
  {
    id: 10,
    name: "Nike Dunk Low Retro White Black Panda",
    description: "Cute Combination of color, Black and White or might as well call it PANDA",
    brand: "Nike",
    image: "/shoes/dunkpanda.avif",
    price: "$50",
    stock: "15",
  },
  {
    id: 11,
    name: "Jordan 1 Retro High OG SP Travis Scott Mocha",
    description: "Travis Scott Jordan 1 Collab",
    brand: "Jordan",
    image: "/shoes/travismocha.avif",
    price: "$700",
    stock: "3",
  },
  {
    id: 12,
    name: "adidas Harden Vol. 8 Black Yellow",
    description: "High Quality, High Performance Basketball Shoes",
    brand: "adidas",
    image: "/shoes/harden.avif",
    price: "$74",
    stock: "9",
  },
  {
    id: 13,
    name: "Jordan 4 Retro Cave Stone",
    description: "Brown-ish Rock color Sneaker",
    brand: "Jordan",
    image: "/shoes/4cavestone.avif",
    price: "$271",
    stock: "4",
  },
  {
    id: 14,
    name: "adidas AE 1 Silver Metallic (Anthony Edwards)",
    description: "High Performance and Flashes like Silver",
    brand: "adidas",
    image: "/shoes/ae1.avif",
    price: "$61",
    stock: "6",
  },
  {
    id: 15,
    name: "Nike Zoom Fly 6 Barely Volt Volt Blue Tint Off Noir",
    description: "Lightweight and Bouncy running shoes",
    brand: "Nike",
    image: "/shoes/zoomfly.avif",
    price: "$99",
    stock: "5",
  },
  {
    id: 16,
    name: "Jordan 11 Retro Playoffs Bred (2019)",
    description: "Jordan's Playoffs Season shoes",
    brand: "Jordan",
    image: "/shoes/11bred.avif",
    price: "$209",
    stock: "8",
  },
  {
    id: 17,
    name: "Nike SB Dunk Low Pro Why So Sad?",
    description: "John Rattray Nike Dunk Collab",
    brand: "Nike",
    image: "/shoes/dunkwss.avif",
    price: "$135",
    stock: "5",
  },
  {
    id: 18,
    name: "adidas Yeezy Boost 350 V2 Bone",
    description: "Comfy and Flexible shoes",
    brand: "adidas",
    image: "/shoes/350pureoat.avif",
    price: "$112",
    stock: "3",
  },
];

export async function GET() {
  return NextResponse.json(shoes);
}
